In [ ]:
import numpy as np

# Creating an array - 1D
a1 = np.array([1, 2, 3, 4, 5])  # list

print(a1)

[1 2 3 4 5]


In [ ]:
a2 = np.random.uniform(0, 1, 10)  # low, high, size
print(a2)
print(a2.shape)  # shape pattern: (rows, columns)
print(a2.dtype)

[0.74089976 0.15852487 0.64736629 0.56570741 0.0774934  0.2341428
 0.17371053 0.23484585 0.77459076 0.41960664]
(10,)
float64


In [ ]:
# create a 2d random array
a3 = np.random.uniform(0, 1, (3, 4))  # shape is a tuple
print(a3)
print(a3.shape)
print(a3.dtype)

[[0.57230185 0.88744253 0.54629096 0.17252791]
 [0.80253955 0.31562787 0.28116691 0.42965246]
 [0.42445482 0.45901112 0.63655469 0.81559899]]
(3, 4)
float64


In [ ]:
# basic array operations
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])
# add, subtract, multiply, divide, modulo
# Element-wise operations
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a % b)

[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]
[0.2 0.5 1.  2.  5. ]
[1 2 0 0 0]


In [10]:
# Matrix operations
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a % b)
print(a @ b)  # Matrix multiplication (dot product)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1 2]
 [3 4]]
[[19 22]
 [43 50]]


In [ ]:
# Indexing and Slicing
a = np.array([1, 2, 3, 4, 5])
print(a[0])
print(a[1:4])